### ISSUE TITLE
ImportError: cannot import name 'VERSION' from 'Infinispan' (unknown location)

### ISSUE THREAD

**Issue by MisoMadao** [infinispan/python-client#19]
I installed the module as per README on my centos 7 with python 3.8.3.
If I try to import anything from the module I get errors.

I can import the module Infinispan but there are no objects I can use from it.

I also added the path to the `libhotrod.so.1.0` library to `LD_LIBRARY_PATH`.

Coming from version 1.0.0b1, I noticed that with the current version the module name now is Infinispan with capital I.
Example of imports that worked in version 1.0.0b1 and do not work anymore now (after changing infinispan to Infinispan):

```
from Infinispan.remotecache import RemoteCache
from Infinispan.remotecache import RemoteCacheError
from Infinispan.remotecache import MAX_VINT as MAX_ENTRY_FIELD_SIZE
```

**Comment by MisoMadao** [comment]
sorry I opened a duplicate
