### ISSUE TITLE
ImportError: cannot import name 'VERSION' from 'Infinispan' (unknown location)

### ISSUE THREAD

**Issue by MisoMadao** [infinispan/python-client#18]
I installed the module as per README on my centos 7 with python 3.8.3.
If I try to import anything from the module I get errors.

I can import the module Infinispan but there are no objects I can use from it.

I also added the path to the `libhotrod.so.1.0` library to `LD_LIBRARY_PATH`.

Coming from version 1.0.0b1, I noticed that with the current version the module name now is Infinispan with capital I.
Example of imports that worked in version 1.0.0b1 and do not work anymore now (after changing infinispan to Infinispan):

```
from Infinispan.remotecache import RemoteCache
from Infinispan.remotecache import RemoteCacheError
from Infinispan.remotecache import MAX_VINT as MAX_ENTRY_FIELD_SIZE
```

**Comment by rigazilla** [comment]
@MisoMadao does the `python3 test.py` from the README works?

**Comment by MisoMadao** [comment]
No I get this:

```
(infinispan-python-client) [infinispan-python-client]$ python test.py 
ERROR [TransportFactory.cpp:256] Initial ping has thrown an exception when pinging localhost:11222 : Failed to connect (host: localhost port: 11222) Operation now in progress
ERROR [RetryOnFailureOperation.h:89] Exception encountered, retry 9 of 10: Failed to connect (host: localhost port: 11222) Operation now in progress
terminate called after throwing an instance of 'infinispan::hotrod::TransportException'
  what():  Failed to connect (host: localhost port: 11222) Operation now in progress
Aborted
```

Should I run something else to make the test work? I'm having the doubt that I miss something here
